import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    'index',
    {
      type: 'category',
      label: 'Start here',
      collapsed: false,
      items: ['getting-started', 'tutorial-todo', 'showcase', 'lexicon'],
    },
    {
      type: 'category',
      label: 'The application',
      items: [
        'hosting-and-options',
        'frame-loop',
        'views-and-navigation',
        'source-generator',
      ],
    },
    {
      type: 'category',
      label: 'Drawing',
      items: ['rendering', 'layout', 'text', 'colours', 'theming'],
    },
    {
      type: 'category',
      label: 'Input',
      items: ['keyboard', 'commands', 'mouse', 'focus', 'ansi'],
    },
    {
      type: 'category',
      label: 'State',
      items: ['atoms', 'stores', 'async-atoms', 'forms', 'state', 'modals'],
    },
    {
      type: 'category',
      label: 'Widgets',
      items: [
        'widgets',
        'lists',
        'table',
        'tree',
        'tabs',
        'scrolling',
        'text-view',
        'status-bar',
        'file-picker',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: ['localization', 'diagnostics', 'testing', 'packages-and-building'],
    },
    {
      type: 'category',
      label: 'Releases',
      items: ['whats-new-in-2.0', 'migrating-to-2.0'],
    },
  ],

  api: [{type: 'autogenerated', dirName: 'api'}],
};

export default sidebars;
