import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: ['index'],
  api: [{type: 'autogenerated', dirName: 'api'}],
};

export default sidebars;
