import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    'index',
    {
      type: 'category',
      label: 'Start here',
      collapsed: false,
      items: ['getting-started', 'tutorial-todo', 'showcase', 'lexicon'],
    },
    {
      type: 'category',
      label: 'The application',
      items: [
        'hosting-and-options',
        'frame-loop',
        'views-and-navigation',
        'source-generator',
      ],
    },
    {
      type: 'category',
      label: 'Drawing',
      items: ['rendering', 'layout', 'text', 'colors', 'theming'],
    },
    {
      type: 'category',
      label: 'Input',
      items: ['keyboard', 'editing', 'commands', 'mouse', 'focus', 'ansi'],
    },
    {
      type: 'category',
      label: 'State',
      items: ['atoms', 'stores', 'async-atoms', 'forms', 'state', 'modals'],
    },
    {
      type: 'category',
      label: 'Widgets',
      items: [
        'widgets',
        'lists',
        'table',
        'tree',
        'tabs',
        'scrolling',
        'text-view',
        'status-bar',
        'charts',
        'pictures',
        'file-picker',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: ['localization', 'diagnostics', 'testing', 'packages-and-building'],
    },
    {
      type: 'category',
      label: 'Releases',
      link: {
        type: 'generated-index',
        title: 'Releases',
        description:
          'What each release changed and what an application has to do about it, newest first.',
        slug: '/releases',
      },
      items: [
        'whats-new-in-2026.8.5',
        'migrating-to-2026.8.5',
        'whats-new-in-2026.8.4',
        'whats-new-in-2026.8.3',
        'whats-new-in-2026.8.2',
        'migrating-to-2026.8.2',
        'whats-new-in-2026.8.1',
        'migrating-to-2026.8.1',
        'whats-new-in-5.0',
        'migrating-to-5.0',
        'whats-new-in-4.0',
        'migrating-to-4.0',
        'whats-new-in-3.0',
        'migrating-to-3.0',
        'whats-new-in-2.0',
        'migrating-to-2.0',
      ],
    },
  ],

  api: [{type: 'autogenerated', dirName: 'api'}],
};

export default sidebars;
